name: EduPlay2
description: "Proyecto escolar EduPlay 2.0 - Aprendizaje Divertido"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.3
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  postgres: ^3.4.3
  shared_preferences: ^2.2.2
  http: ^1.2.0
  crypto: ^3.0.7
  # Agregado para reproducir AppTec.mp4
  video_player: ^2.8.6 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0D1B2A"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/avatars/
    # Agregados para el SplashScreen
    - assets/AppTec.mp4
    - assets/fondo_aventura.gif  # <-- Nombre actualizado